module_name: Block Contact
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - cms pages
  - cms
  - cms links
description_short: The block contact allows you to enter contact information for your site's customer service.
description: description.md
images:
  - image-1.png
license: MIT
